### ISSUE TITLE
what do multiple families listed in an individual hit mean?

### ISSUE THREAD

**Issue by sp-srivas** [bergmanlab/TELR#17]
hello, 

thanks for developing this useful tool for long reads. I have gotten a few hits in Dmel with multiple families listed in the same entry. 
For example: 
2L      15001967        15001970        DM_17.6|DM_297  .       +
2L      15876072        15876083        Doc|Juan        .       +
2L      17936947        17936951        Burdock|roo     .       -
2L      20539607        20539621        Rt1a|Rt1b       .       -

Does this mean homology to 17.6 and 297 was found after locus assembly or that both families have insertions there creating a complex (nested) insertion? If the later is the case, which one is the parent insertion and which one is the nested?

**Comment by shunhuahan** [comment]
Hi @sp-srivas, thanks for the question!

Basically, TELR uses RepeatMasker+minimap2 to annotate TE families in the locally assembled contig (annotation 1). TELR also aligns the insertion sequences from Sniffles VCF to the locally assembled contig (annotation 2). The annotation 1 is then filtered to only keep insertions that overlap annotation 2. Finally, the sequences that flank the filtered annotation 1 in the local contig will be extracted and realigned to the reference genome to identify precise insertion coordinate. TELR would only report the insertion if 5' and 3' flanking sequences are aligned close to each other. Therefore, the multiple families are most likely caused by complex nested insertion events in the current implementation. Let me know if you have more questions on interpreting the TELR predictions.

Shunhua

**Comment by sp-srivas** [comment]
Thanks so much, @shunhuahan! This helps with the interpretation.
